[package]
name = "neoncrypto"
version = "0.1.0"
authors = ["Tobias Frei <mail@tobiasfrei.ch>"]
license = "MIT"
build = "build.rs"

[lib]
name = "neoncrypto"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
